Various tweaks, main one being to fix Neovim diff

diff --git a/git-vdiff b/git-vdiff
--- a/git-vdiff
+++ b/git-vdiff
@@ -1,14 +1,18 @@
 #!/bin/sh
 
+# Create a temporary file when diffing new or deleted files.
+empty_file=$(mktemp)
+
+# Ensure temporary file cleanup on exit, including abnormal termination.
+trap 'rm -f "$empty_file"' EXIT
+
 # Custom Git diff command.
 #
-# This command will substitute '/dev/null' usage with '/dev/zero'. Use of
-# '/dev/null' results in Neovim read errors when run on macOS.
-
+# This command will substitute '/dev/null' usage with '$empty_file'.
 if [ "$1" = "/dev/null" ]; then
-    nvim -d /dev/zero "$2"
+    NVIM_DISABLE_LSP=1 nvim -d "$empty_file" "$2"
 elif [ "$2" = "/dev/null" ]; then
-    nvim -d "$1" /dev/zero
+    NVIM_DISABLE_LSP=1 nvim -d "$1" "$empty_file"
 else
-    nvim -d "$1" "$2"
+    NVIM_DISABLE_LSP=1 nvim -d "$1" "$2"
 fi
